import fs from 'node:fs/promises'; import path from 'node:path'; import { spawn } from 'node:child_process'; import { sql, getSettings, type Article } from './db'; import { getVideoDimensions, normalizeVideoSettings, type VideoSettings } from './video-settings';
const outDir=path.join(process.cwd(),'public','generated');
async function ensure(){ await fs.mkdir(outDir,{recursive:true}); }
export async function runPipeline(articleId:number){ await ensure(); const a=sql.prepare('select * from articles where id=?').get(articleId) as Article; if(!a) throw new Error('Article not found');
  const settings=getSettings() as any; const videoSettings = normalizeVideoSettings(settings); const plan = await planVideo(a, settings, videoSettings); const rewritten = plan.script; const imagePrompt = plan.imagePrompt;
  const renderSettings = { ...videoSettings, lowerThirdText: plan.lowerThird || videoSettings.lowerThirdText };
  await writeProductionBrief(articleId, plan, renderSettings);
  sql.prepare('update articles set rewrittenText=?, imagePrompt=?, status=?, updatedAt=CURRENT_TIMESTAMP where id=?').run(rewritten,imagePrompt,'scripted',articleId);
  const audio= await synthesize(articleId, rewritten, settings); const image= await createImage(articleId, imagePrompt, settings, renderSettings); const video= await createVideo(articleId, audio, image, a, renderSettings);
  sql.prepare('update articles set audioPath=?, imagePath=?, videoPath=?, status=?, updatedAt=CURRENT_TIMESTAMP where id=?').run(audio,image,video,'video_ready',articleId); return video; }
type VideoPlan = { script: string; imagePrompt: string; title: string; description: string; chapters: string[]; lowerThird: string; safetyNotes: string[] };
async function planVideo(a:Article, s:any, videoSettings: VideoSettings): Promise<VideoPlan>{
  const fallback = buildFallbackPlan(a, videoSettings);
  if(!s.openRouterKey || !videoSettings.aiEnhancementEnabled) return fallback;
  const schema = { type:'object', properties:{ script:{type:'string'}, imagePrompt:{type:'string'}, title:{type:'string'}, description:{type:'string'}, chapters:{type:'array',items:{type:'string'}}, lowerThird:{type:'string'}, safetyNotes:{type:'array',items:{type:'string'}} }, required:['script','imagePrompt','title','description','chapters','lowerThird','safetyNotes'], additionalProperties:false };
  const modeHints: Record<string,string> = { balanced:'kompakt, verständlich, mit Einordnung', shorts:'sehr schnell, hookstark, vertikal geeignet', deepDive:'ausführlicher Hintergrund mit klaren Abschnitten', breaking:'dringend, aber ohne Spekulation' };
  try{
    const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${s.openRouterKey}`,'Content-Type':'application/json','HTTP-Referer':'http://localhost:3000','X-Title':'YouTube News Automation'},body:JSON.stringify({model:s.openRouterTextModel||'openai/gpt-4.1-mini',messages:[{role:'system',content:`Du bist ein deutschsprachiger YouTube-News-Produzent. Erstelle ein sendefertiges Videokonzept als JSON. Nutze keine erfundenen Fakten. Stil: ${modeHints[videoSettings.aiScriptMode]}. Ton: ${videoSettings.aiTone}. Zielgruppe: ${videoSettings.aiAudience}. Zieldauer: ${videoSettings.aiTargetDuration} Sekunden. Hook gewünscht: ${videoSettings.aiIncludeHook ? 'ja' : 'nein'}. Kapitel gewünscht: ${videoSettings.aiIncludeChapters ? 'ja' : 'nein'}. Faktenregel: ${videoSettings.aiFactCheckPrompt}. CTA: ${videoSettings.callToAction}`},{role:'user',content:`Titel: ${a.title}
Quelle-URL: ${a.url}
Rohtext: ${a.rawText}`}],temperature:.55,response_format:{type:'json_schema',json_schema:{name:'youtube_news_video_plan',strict:true,schema}}})});
    if(!r.ok) throw new Error(await r.text());
    const j:any=await r.json(); const content=j.choices?.[0]?.message?.content; const parsed=JSON.parse(content);
    return { script: String(parsed.script || fallback.script), imagePrompt: `${videoSettings.thumbnailStyle} ${videoSettings.aiImagePromptStyle}: ${parsed.imagePrompt || a.title}`, title: String(parsed.title || fallback.title), description: String(parsed.description || fallback.description), chapters: Array.isArray(parsed.chapters)?parsed.chapters.map(String):fallback.chapters, lowerThird: String(parsed.lowerThird || fallback.lowerThird), safetyNotes: Array.isArray(parsed.safetyNotes)?parsed.safetyNotes.map(String):[] };
  }catch(error){
    return { ...fallback, safetyNotes:[`KI-Planung fehlgeschlagen, Fallback genutzt: ${error instanceof Error ? error.message.slice(0,180) : 'unbekannter Fehler'}`] };
  }
}
function buildFallbackPlan(a:Article, videoSettings: VideoSettings): VideoPlan{ const script=`Breaking News: ${a.title}. ${a.rawText}

${videoSettings.callToAction}`; return { script, imagePrompt:`${videoSettings.thumbnailStyle} YouTube news thumbnail, ${videoSettings.aiImagePromptStyle}: ${a.title}`, title:a.title, description:a.rawText.slice(0,280), chapters:videoSettings.aiIncludeChapters?['00:00 Überblick','00:20 Einordnung','00:45 Was jetzt wichtig ist']:[], lowerThird:videoSettings.lowerThirdText || 'Aktuelle Nachrichten', safetyNotes:[] }; }
async function writeProductionBrief(id:number, plan:VideoPlan, videoSettings: VideoSettings){ const brief=[`# Produktionsbrief Artikel ${id}`,`Titel: ${plan.title}`,`Bauchbinde: ${plan.lowerThird}`,`Format: ${videoSettings.aspectRatio} ${videoSettings.resolution}`,``, `Beschreibung:`, plan.description, ``, `Kapitel:`, ...plan.chapters.map(c=>`- ${c}`), ``, `Sicherheitsnotizen:`, ...(plan.safetyNotes.length ? plan.safetyNotes.map(n=>`- ${n}`) : ['- Keine'])].join('\n'); await fs.writeFile(path.join(outDir,`article-${id}-brief.md`), brief); }
async function synthesize(id:number, text:string, s:any){ const file=`/generated/article-${id}.wav`; const full=path.join(process.cwd(),'public',file); if(s.elevenLabsKey){ const voice=s.elevenLabsVoiceId||'21m00Tcm4TlvDq8ikWAM'; const r=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voice}`,{method:'POST',headers:{'xi-api-key':s.elevenLabsKey,'Content-Type':'application/json'},body:JSON.stringify({text,model_id:'eleven_multilingual_v2'})}); await fs.writeFile(full, Buffer.from(await r.arrayBuffer())); return file; } await run('ffmpeg',['-y','-f','lavfi','-i','sine=frequency=440:duration=8','-ar','44100',full]); await fs.writeFile(path.join(outDir,`article-${id}.txt`), text); return file; }
async function createImage(id:number, prompt:string, s:any, videoSettings: VideoSettings){ const file=`/generated/article-${id}.svg`; const esc=xml(prompt); const {width,height}=getVideoDimensions(videoSettings); await fs.writeFile(path.join(process.cwd(),'public',file),`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="${videoSettings.backgroundColor}"/><stop offset="1" stop-color="${videoSettings.accentColor}"/></linearGradient></defs><rect fill="url(#g)" width="100%" height="100%"/><text x="70" y="${Math.round(height/2)}" fill="white" font-size="54" font-family="Arial">${esc.slice(0,120)}</text></svg>`); return file; }
async function createVideo(id:number, audio:string, image:string, article: Article, videoSettings: VideoSettings){ const file=`/generated/article-${id}.mp4`; const full=path.join(process.cwd(),'public',file); const {width,height}=getVideoDimensions(videoSettings); const main=`/generated/article-${id}-main.mp4`; await renderStillVideo(path.join(process.cwd(),'public',image), path.join(process.cwd(),'public',audio), path.join(process.cwd(),'public',main), width, height, videoSettings, article.title);
  const segments:string[]=[];
  const intro=await createBumper(id,'intro',videoSettings.introMode,videoSettings.introText,videoSettings.introDuration,videoSettings.introAssetPath,videoSettings,width,height);
  if(intro) segments.push(intro); segments.push(path.join(process.cwd(),'public',main));
  const outro=await createBumper(id,'outro',videoSettings.outroMode,videoSettings.outroText,videoSettings.outroDuration,videoSettings.outroAssetPath,videoSettings,width,height);
  if(outro) segments.push(outro);
  if(segments.length===1){ await fs.rename(path.join(process.cwd(),'public',main), full); return file; }
  const list=path.join(outDir,`article-${id}-concat.txt`); await fs.writeFile(list, segments.map(p=>`file '${p.replace(/'/g,"'\\''")}'`).join('\n'));
  await run('ffmpeg',['-y','-f','concat','-safe','0','-i',list,'-c','copy',full]); return file; }
async function renderStillVideo(imagePath:string, audioPath:string, outputPath:string, width:number, height:number, videoSettings: VideoSettings, title:string){ const vf=[`scale=${width}:${height}:force_original_aspect_ratio=increase`,`crop=${width}:${height}`,`format=yuv420p`]; if(videoSettings.lowerThirdEnabled) vf.push(`drawbox=x=0:y=${height-132}:w=${width}:h=92:color=black@0.55:t=fill`,`drawtext=text='${ffmpegText(videoSettings.lowerThirdText || title)}':x=48:y=${height-98}:fontsize=34:fontcolor=white`); await run('ffmpeg',['-y','-loop','1','-i',imagePath,'-i',audioPath,'-vf',vf.join(','),'-c:v','libx264','-tune','stillimage','-c:a','aac','-shortest','-pix_fmt','yuv420p',outputPath]); }
async function createBumper(id:number, slot:'intro'|'outro', mode:string, text:string, duration:number, assetPath:string, videoSettings: VideoSettings, width:number, height:number){ if(mode==='none') return null; const out=path.join(outDir,`article-${id}-${slot}.mp4`); let input=assetPath ? path.join(process.cwd(),'public',assetPath.startsWith('/') ? assetPath : `/${assetPath}`) : ''; if(mode==='generated' || !input){ const svg=`/generated/article-${id}-${slot}.svg`; await fs.writeFile(path.join(process.cwd(),'public',svg),`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect fill="${videoSettings.backgroundColor}" width="100%" height="100%"/><circle cx="${width-130}" cy="120" r="90" fill="${videoSettings.accentColor}" opacity=".85"/><text x="70" y="${Math.round(height/2)}" fill="white" font-size="60" font-family="Arial" font-weight="700">${xml(text).slice(0,80)}</text></svg>`); input=path.join(process.cwd(),'public',svg); }
  const isVideo=/\.(mp4|mov|webm|mkv)$/i.test(input); const inputArgs=isVideo ? ['-i',input] : ['-loop','1','-i',input];
  await run('ffmpeg',['-y',...inputArgs,'-f','lavfi','-i',`anullsrc=channel_layout=stereo:sample_rate=44100`,'-t',String(duration),'-vf',`scale=${width}:${height}:force_original_aspect_ratio=increase,crop=${width}:${height},format=yuv420p`,'-c:v','libx264','-c:a','aac','-shortest',out]); return out; }
function xml(value:string){ return value.replace(/[<&>]/g,''); }
function ffmpegText(value:string){ return value.replace(/[\\':]/g,'\\$&').slice(0,90); }
function run(cmd:string,args:string[]){ return new Promise<void>((res,rej)=>{ const p=spawn(cmd,args); let e=''; p.stderr.on('data',d=>e+=d); p.on('close',c=>c===0?res():rej(new Error(e))); }); }
