import fs from 'node:fs/promises'; import path from 'node:path'; import { spawn } from 'node:child_process'; import { sql, getSettings, type Article } from './db'; import { getVideoDimensions, normalizeVideoSettings, type VideoSettings } from './video-settings';
const outDir=path.join(process.cwd(),'public','generated');
async function ensure(){ await fs.mkdir(outDir,{recursive:true}); }
export async function runPipeline(articleId:number){ await ensure(); const a=sql.prepare('select * from articles where id=?').get(articleId) as Article; if(!a) throw new Error('Article not found');
  const settings=getSettings() as any; const videoSettings = normalizeVideoSettings(settings); const rewritten= await rewrite(a, settings, videoSettings); const imagePrompt=`${videoSettings.thumbnailStyle} YouTube news thumbnail, cinematic editorial image: ${a.title}`;
  sql.prepare('update articles set rewrittenText=?, imagePrompt=?, status=?, updatedAt=CURRENT_TIMESTAMP where id=?').run(rewritten,imagePrompt,'scripted',articleId);
  const audio= await synthesize(articleId, rewritten, settings); const image= await createImage(articleId, imagePrompt, settings, videoSettings); const video= await createVideo(articleId, audio, image, a, videoSettings);
  sql.prepare('update articles set audioPath=?, imagePath=?, videoPath=?, status=?, updatedAt=CURRENT_TIMESTAMP where id=?').run(audio,image,video,'video_ready',articleId); return video; }
async function rewrite(a:Article, s:any, videoSettings: VideoSettings){ if(s.openRouterKey){ const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${s.openRouterKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:s.openRouterTextModel||'openai/gpt-4.1-mini',messages:[{role:'system',content:`Formuliere eine kurze deutsche YouTube-News als originellen Sprechertext um. Keine Plagiate. Beachte den gewünschten Call-to-Action am Ende, falls passend: ${videoSettings.callToAction}`},{role:'user',content:`Titel: ${a.title}\nQuelle: ${a.rawText}`}],temperature:.7})}); const j:any=await r.json(); return j.choices?.[0]?.message?.content || a.rawText; } return `Breaking News: ${a.title}. ${a.rawText}`; }
async function synthesize(id:number, text:string, s:any){ const file=`/generated/article-${id}.wav`; const full=path.join(process.cwd(),'public',file); if(s.elevenLabsKey){ const voice=s.elevenLabsVoiceId||'21m00Tcm4TlvDq8ikWAM'; const r=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voice}`,{method:'POST',headers:{'xi-api-key':s.elevenLabsKey,'Content-Type':'application/json'},body:JSON.stringify({text,model_id:'eleven_multilingual_v2'})}); await fs.writeFile(full, Buffer.from(await r.arrayBuffer())); return file; } await run('ffmpeg',['-y','-f','lavfi','-i','sine=frequency=440:duration=8','-ar','44100',full]); await fs.writeFile(path.join(outDir,`article-${id}.txt`), text); return file; }
async function createImage(id:number, prompt:string, s:any, videoSettings: VideoSettings){ const file=`/generated/article-${id}.svg`; const esc=xml(prompt); const {width,height}=getVideoDimensions(videoSettings); await fs.writeFile(path.join(process.cwd(),'public',file),`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="${videoSettings.backgroundColor}"/><stop offset="1" stop-color="${videoSettings.accentColor}"/></linearGradient></defs><rect fill="url(#g)" width="100%" height="100%"/><text x="70" y="${Math.round(height/2)}" fill="white" font-size="54" font-family="Arial">${esc.slice(0,120)}</text></svg>`); return file; }
async function createVideo(id:number, audio:string, image:string, article: Article, videoSettings: VideoSettings){ const file=`/generated/article-${id}.mp4`; const full=path.join(process.cwd(),'public',file); const {width,height}=getVideoDimensions(videoSettings); const main=`/generated/article-${id}-main.mp4`; await renderStillVideo(path.join(process.cwd(),'public',image), path.join(process.cwd(),'public',audio), path.join(process.cwd(),'public',main), width, height, videoSettings, article.title);
  const segments:string[]=[];
  const intro=await createBumper(id,'intro',videoSettings.introMode,videoSettings.introText,videoSettings.introDuration,videoSettings.introAssetPath,videoSettings,width,height);
  if(intro) segments.push(intro); segments.push(path.join(process.cwd(),'public',main));
  const outro=await createBumper(id,'outro',videoSettings.outroMode,videoSettings.outroText,videoSettings.outroDuration,videoSettings.outroAssetPath,videoSettings,width,height);
  if(outro) segments.push(outro);
  if(segments.length===1){ await fs.rename(path.join(process.cwd(),'public',main), full); return file; }
  const list=path.join(outDir,`article-${id}-concat.txt`); await fs.writeFile(list, segments.map(p=>`file '${p.replace(/'/g,"'\\''")}'`).join('\n'));
  await run('ffmpeg',['-y','-f','concat','-safe','0','-i',list,'-c','copy',full]); return file; }
async function renderStillVideo(imagePath:string, audioPath:string, outputPath:string, width:number, height:number, videoSettings: VideoSettings, title:string){ const vf=[`scale=${width}:${height}:force_original_aspect_ratio=increase`,`crop=${width}:${height}`,`format=yuv420p`]; if(videoSettings.lowerThirdEnabled) vf.push(`drawbox=x=0:y=${height-132}:w=${width}:h=92:color=black@0.55:t=fill`,`drawtext=text='${ffmpegText(videoSettings.lowerThirdText || title)}':x=48:y=${height-98}:fontsize=34:fontcolor=white`); await run('ffmpeg',['-y','-loop','1','-i',imagePath,'-i',audioPath,'-vf',vf.join(','),'-c:v','libx264','-tune','stillimage','-c:a','aac','-shortest','-pix_fmt','yuv420p',outputPath]); }
async function createBumper(id:number, slot:'intro'|'outro', mode:string, text:string, duration:number, assetPath:string, videoSettings: VideoSettings, width:number, height:number){ if(mode==='none') return null; const out=path.join(outDir,`article-${id}-${slot}.mp4`); let input=assetPath ? path.join(process.cwd(),'public',assetPath.startsWith('/') ? assetPath : `/${assetPath}`) : ''; if(mode==='generated' || !input){ const svg=`/generated/article-${id}-${slot}.svg`; await fs.writeFile(path.join(process.cwd(),'public',svg),`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect fill="${videoSettings.backgroundColor}" width="100%" height="100%"/><circle cx="${width-130}" cy="120" r="90" fill="${videoSettings.accentColor}" opacity=".85"/><text x="70" y="${Math.round(height/2)}" fill="white" font-size="60" font-family="Arial" font-weight="700">${xml(text).slice(0,80)}</text></svg>`); input=path.join(process.cwd(),'public',svg); }
  const isVideo=/\.(mp4|mov|webm|mkv)$/i.test(input); const inputArgs=isVideo ? ['-i',input] : ['-loop','1','-i',input];
  await run('ffmpeg',['-y',...inputArgs,'-f','lavfi','-i',`anullsrc=channel_layout=stereo:sample_rate=44100`,'-t',String(duration),'-vf',`scale=${width}:${height}:force_original_aspect_ratio=increase,crop=${width}:${height},format=yuv420p`,'-c:v','libx264','-c:a','aac','-shortest',out]); return out; }
function xml(value:string){ return value.replace(/[<&>]/g,''); }
function ffmpegText(value:string){ return value.replace(/[\\':]/g,'\\$&').slice(0,90); }
function run(cmd:string,args:string[]){ return new Promise<void>((res,rej)=>{ const p=spawn(cmd,args); let e=''; p.stderr.on('data',d=>e+=d); p.on('close',c=>c===0?res():rej(new Error(e))); }); }
