import fs from 'node:fs/promises'; import path from 'node:path'; import { spawn } from 'node:child_process'; import { sql, getSettings, type Article } from './db';
const outDir=path.join(process.cwd(),'public','generated');
async function ensure(){ await fs.mkdir(outDir,{recursive:true}); }
export async function runPipeline(articleId:number){ await ensure(); const a=sql.prepare('select * from articles where id=?').get(articleId) as Article; if(!a) throw new Error('Article not found');
  const settings=getSettings() as any; const rewritten= await rewrite(a, settings); const imagePrompt=`Modern YouTube news thumbnail, cinematic editorial image: ${a.title}`;
  sql.prepare('update articles set rewrittenText=?, imagePrompt=?, status=?, updatedAt=CURRENT_TIMESTAMP where id=?').run(rewritten,imagePrompt,'scripted',articleId);
  const audio= await synthesize(articleId, rewritten, settings); const image= await createImage(articleId, imagePrompt, settings); const video= await createVideo(articleId, audio, image);
  sql.prepare('update articles set audioPath=?, imagePath=?, videoPath=?, status=?, updatedAt=CURRENT_TIMESTAMP where id=?').run(audio,image,video,'video_ready',articleId); return video; }
async function rewrite(a:Article, s:any){ if(s.openRouterKey){ const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${s.openRouterKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:s.openRouterTextModel||'openai/gpt-4.1-mini',messages:[{role:'system',content:'Formuliere eine kurze deutsche YouTube-News als originellen Sprechertext um. Keine Plagiate.'},{role:'user',content:`Titel: ${a.title}\nQuelle: ${a.rawText}`}],temperature:.7})}); const j:any=await r.json(); return j.choices?.[0]?.message?.content || a.rawText; } return `Breaking News: ${a.title}. ${a.rawText}`; }
async function synthesize(id:number, text:string, s:any){ const file=`/generated/article-${id}.wav`; const full=path.join(process.cwd(),'public',file); if(s.elevenLabsKey){ const voice=s.elevenLabsVoiceId||'21m00Tcm4TlvDq8ikWAM'; const r=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voice}`,{method:'POST',headers:{'xi-api-key':s.elevenLabsKey,'Content-Type':'application/json'},body:JSON.stringify({text,model_id:'eleven_multilingual_v2'})}); await fs.writeFile(full, Buffer.from(await r.arrayBuffer())); return file; } await run('ffmpeg',['-y','-f','lavfi','-i','sine=frequency=440:duration=8','-ar','44100',full]); await fs.writeFile(path.join(outDir,`article-${id}.txt`), text); return file; }
async function createImage(id:number, prompt:string, s:any){ const file=`/generated/article-${id}.svg`; const esc=prompt.replace(/[<&>]/g,''); await fs.writeFile(path.join(process.cwd(),'public',file),`<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#111827"/><stop offset="1" stop-color="#dc2626"/></linearGradient></defs><rect fill="url(#g)" width="100%" height="100%"/><text x="70" y="360" fill="white" font-size="54" font-family="Arial">${esc.slice(0,120)}</text></svg>`); return file; }
async function createVideo(id:number, audio:string, image:string){ const file=`/generated/article-${id}.mp4`; await run('ffmpeg',['-y','-loop','1','-i',path.join(process.cwd(),'public',image),'-i',path.join(process.cwd(),'public',audio),'-c:v','libx264','-tune','stillimage','-c:a','aac','-shortest','-pix_fmt','yuv420p',path.join(process.cwd(),'public',file)]); return file; }
function run(cmd:string,args:string[]){ return new Promise<void>((res,rej)=>{ const p=spawn(cmd,args); let e=''; p.stderr.on('data',d=>e+=d); p.on('close',c=>c===0?res():rej(new Error(e))); }); }
