export type SourcePreset = {
  name: string;
  url: string;
  description: string;
  intervalMinutes: number;
  category: string;
};

export const sourcePresets: SourcePreset[] = [
  {
    name: 'BILD.de Startseite',
    url: 'https://www.bild.de',
    description: 'Große Boulevard-News-Startseite zum Testen der HTML- und JSON-LD-Erkennung.',
    intervalMinutes: 30,
    category: 'Boulevard',
  },
  {
    name: 'Tagesschau Inland',
    url: 'https://www.tagesschau.de/inland/',
    description: 'Öffentlich-rechtliche Inlandsnachrichten als stabiler HTML-Test für seriöse Meldungen.',
    intervalMinutes: 45,
    category: 'Nachrichten',
  },
  {
    name: 'heise online News',
    url: 'https://www.heise.de/rss/heise-atom.xml',
    description: 'RSS/Atom-Feed für Technik- und Digitalthemen mit zuverlässigen Metadaten.',
    intervalMinutes: 60,
    category: 'Technik',
  },
  {
    name: 'DW Deutsch',
    url: 'https://rss.dw.com/rdf/rss-de-all',
    description: 'RSS-Feed der Deutschen Welle für internationale Themen auf Deutsch.',
    intervalMinutes: 60,
    category: 'International',
  },
  {
    name: 'NuoFlix Mediathek',
    url: 'https://nuoflix.de/',
    description: 'NuoFlix-Webseite mit aktuellen Videos, Gesprächen und Sendungen; wird über die HTML-Karten erkannt.',
    intervalMinutes: 60,
    category: 'Alternativmedien',
  },
  {
    name: 'NuoViso Videos',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCPOmsF_XgQohcJhdj58zshg',
    description: 'Offizieller YouTube-Atom-Feed des NuoViso-Kanals.',
    intervalMinutes: 60,
    category: 'Alternativmedien',
  },
  {
    name: 'Kontrafunk aktuell',
    url: 'https://www.spreaker.com/show/5602119/episodes/feed',
    description: 'Podcast-RSS des täglichen Nachrichtenmagazins KONTRAFUNK aktuell.',
    intervalMinutes: 60,
    category: 'Alternativmedien',
  },
  {
    name: 'apolut',
    url: 'https://apolut.net/rss/',
    description: 'RSS-Feed mit Artikeln, Kommentaren, Interviews und Videoformaten von apolut.',
    intervalMinutes: 60,
    category: 'Alternativmedien',
  },
  {
    name: 'apolut Podcast',
    url: 'https://apolut.net/podcast/rss',
    description: 'Separater Podcast-RSS von apolut für Audio- und Gesprächsformate.',
    intervalMinutes: 60,
    category: 'Podcast',
  },
  {
    name: 'NachDenkSeiten',
    url: 'https://www.nachdenkseiten.de/?feed=rss2',
    description: 'RSS2-Feed der NachDenkSeiten mit politischen Analysen und Hinweisen.',
    intervalMinutes: 60,
    category: 'Alternativmedien',
  },
  {
    name: 'NachDenkSeiten Audio',
    url: 'https://www.nachdenkseiten.de/?feed=podcast',
    description: 'Podcast-RSS mit vertonten Beiträgen und Interviews der NachDenkSeiten.',
    intervalMinutes: 90,
    category: 'Podcast',
  },
  {
    name: 'Multipolar',
    url: 'https://multipolar-magazin.de/atom.xml',
    description: 'Offizieller Atom-Feed des Multipolar-Magazins.',
    intervalMinutes: 90,
    category: 'Alternativmedien',
  },
  {
    name: 'Overton Magazin',
    url: 'https://overton-magazin.de/feed/',
    description: 'RSS-Feed des Debatten- und Autorenmagazins Overton.',
    intervalMinutes: 60,
    category: 'Alternativmedien',
  },
  {
    name: 'Manova',
    url: 'https://www.manova.news/artikel.atom',
    description: 'Atom-Feed der Artikel des Manova-Magazins.',
    intervalMinutes: 90,
    category: 'Alternativmedien',
  },
  {
    name: 'Tichys Einblick',
    url: 'https://www.tichyseinblick.de/feed/',
    description: 'Offizieller RSS-Feed von Tichys Einblick.',
    intervalMinutes: 45,
    category: 'Meinung',
  },
  {
    name: 'Achgut',
    url: 'https://www.achgut.com/rss2',
    description: 'Kostenfreier RSS-Feed der Achse des Guten ohne Volltexte.',
    intervalMinutes: 60,
    category: 'Meinung',
  },
  {
    name: 'Reitschuster',
    url: 'https://reitschuster.de/feed/',
    description: 'Offizieller RSS-Feed von reitschuster.de.',
    intervalMinutes: 45,
    category: 'Alternativmedien',
  },
  {
    name: 'Junge Freiheit',
    url: 'https://jungefreiheit.de/feed/',
    description: 'Offizieller Nachrichten-Feed der Jungen Freiheit.',
    intervalMinutes: 45,
    category: 'Meinung',
  },
  {
    name: 'TKP',
    url: 'https://tkp.at/feed/',
    description: 'RSS-Feed des österreichischen Blogs TKP.',
    intervalMinutes: 60,
    category: 'Alternativmedien',
  },
  {
    name: 'Transition News',
    url: 'https://transition-news.org/spip.php?page=backend',
    description: 'Offizieller SPIP-RSS-Feed von Transition News.',
    intervalMinutes: 60,
    category: 'Alternativmedien',
  },
  {
    name: 'Anti-Spiegel',
    url: 'https://anti-spiegel.ru/feed/',
    description: 'RSS-Feed von Anti-Spiegel; funktioniert auch wenn die Startseite automatisierte Zugriffe blockiert.',
    intervalMinutes: 60,
    category: 'Alternativmedien',
  },
  {
    name: 'Uncut News',
    url: 'https://uncutnews.ch/feed/',
    description: 'RSS-Feed des Schweizer Portals Uncut News.',
    intervalMinutes: 60,
    category: 'Alternativmedien',
  },
  {
    name: 'Norbert Häring – Geld und mehr',
    url: 'https://norberthaering.de/feed/',
    description: 'RSS-Feed des Wirtschafts- und Gesellschaftsblogs von Norbert Häring.',
    intervalMinutes: 120,
    category: 'Wirtschaft',
  },
  {
    name: 'Norbert Häring Podcast',
    url: 'https://norberthaering.de/feed/podcast',
    description: 'Podcast-RSS des Blogs Geld und mehr.',
    intervalMinutes: 180,
    category: 'Podcast',
  },
  {
    name: 'Telepolis',
    url: 'https://www.telepolis.de/feed.xml',
    description: 'Offizieller Telepolis-Feed für Politik, Gesellschaft, Wissenschaft und Technik.',
    intervalMinutes: 45,
    category: 'Debatte',
  },
  {
    name: 'Cicero',
    url: 'https://www.cicero.de/rss.xml',
    description: 'Offizieller RSS-Feed des politischen Magazins Cicero.',
    intervalMinutes: 60,
    category: 'Debatte',
  },
  {
    name: 'Wikihausen',
    url: 'https://wikihausen.de/feed/',
    description: 'RSS-Feed des Video-Blogs von Markus Fiedler.',
    intervalMinutes: 120,
    category: 'Medienkritik',
  },
  {
    name: 'DrBines verbales Vitriol',
    url: 'https://drbine.substack.com/feed',
    description: 'Substack-RSS von Sabine Stebel.',
    intervalMinutes: 120,
    category: 'Gastautoren',
  },
  {
    name: 'Uwe Boll Podcast Network',
    url: 'https://anchor.fm/s/6c4d6144/podcast/rss',
    description: 'Podcast-RSS des Uwe Boll Podcast Network.',
    intervalMinutes: 180,
    category: 'Podcast',
  },
  {
    name: 'Max Otte',
    url: 'https://max-otte.de/feed/',
    description: 'RSS-Feed der persönlichen Webseite von Max Otte, der in den untersuchten NuoFlix-Beiträgen genannt wird.',
    intervalMinutes: 180,
    category: 'Gastautoren',
  },
];
